from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    ProductViewSet,
    ShopViewSet,
    SignupView,
    LoginView,
    TokenRefreshView,
    SendOTPView,
    VerifyOTPView,
    ProductListView,
    ProductSearchView,
    ProductDetailView,
    ShopDetailView,
    ShopRankingView,
    CheckoutView,
    MyOrdersView,
    ShopOrdersView,
    AcceptOrderView,
    RejectOrderView,
    AdvanceOrderView,
    ProductShopsView,
    OrderDetailView,
    CategoryListView,
    WishlistViewSet,
    ShopAnalyticsView,
    ShopProductsListView,
    ShopToggleLiveInventoryView,
    RiderStatusToggleView,
    RiderDashboardView,
    RiderDashboardView,
    UpdateDeliveryAssignmentView,
    DeliveryRecommendationView,
    ShopDemandForecastView,
)
from .dashboard_views import (
    ShopRevenueTodayView,
    ShopRevenueMonthView,
    ShopTopProductsView,
    MarketSearchTrendsView,
    ShopLowStockView,
    ShopOutOfStockView,
    ShopExpiringProductsView,
    ShopSlowMovingProductsView,
    ShopWeatherView,
)

router = DefaultRouter()
router.register(r'products', ProductViewSet, basename='product')
router.register(r'shops', ShopViewSet, basename='shop')
router.register(r'wishlist', WishlistViewSet, basename='wishlist')

urlpatterns = [
    path('auth/signup/', SignupView.as_view(), name='signup'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('auth/send-otp/', SendOTPView.as_view(), name='send_otp'),
    path('auth/verify-otp/', VerifyOTPView.as_view(), name='verify_otp'),
    path('products/list/', ProductListView.as_view(), name='product_list'),
    path('products/search/', ProductSearchView.as_view(), name='product_search'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('products/detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/shops/', ProductShopsView.as_view(), name='product_shops'),
    path('shops/detail/<int:pk>/', ShopDetailView.as_view(), name='shop_detail'),
    path('shops/ranking/', ShopRankingView.as_view(), name='shop_ranking'),
    path('shops/analytics/', ShopAnalyticsView.as_view(), name='shop_analytics'),
    path('shops/demand-forecast/', ShopDemandForecastView.as_view(), name='shop_demand_forecast'),
    path('shop/dashboard/revenue-today/', ShopRevenueTodayView.as_view(), name='dashboard_revenue_today'),
    path('shop/dashboard/revenue-month/', ShopRevenueMonthView.as_view(), name='dashboard_revenue_month'),
    path('shop/dashboard/top-products/', ShopTopProductsView.as_view(), name='dashboard_top_products'),
    path('shop/dashboard/search-trends/', MarketSearchTrendsView.as_view(), name='dashboard_search_trends'),
    path('shop/dashboard/low-stock/', ShopLowStockView.as_view(), name='dashboard_low_stock'),
    path('shop/dashboard/out-of-stock/', ShopOutOfStockView.as_view(), name='dashboard_out_of_stock'),
    path('shop/dashboard/expiring-products/', ShopExpiringProductsView.as_view(), name='dashboard_expiring_products'),
    path('shop/dashboard/slow-moving/', ShopSlowMovingProductsView.as_view(), name='dashboard_slow_moving'),
    path('shop/dashboard/weather/', ShopWeatherView.as_view(), name='dashboard_weather'),

    path('shops/my-products/', ShopProductsListView.as_view(), name='shop_my_products'),
    path('shops/toggle-live/', ShopToggleLiveInventoryView.as_view(), name='shop_toggle_live'),
    path('riders/toggle-online/', RiderStatusToggleView.as_view(), name='rider_toggle_online'),
    path('riders/dashboard/', RiderDashboardView.as_view(), name='rider_dashboard'),
    path('riders/assignments/update/', UpdateDeliveryAssignmentView.as_view(), name='rider_assignment_update'),
    path('orders/checkout/', CheckoutView.as_view(), name='checkout'),
    path('orders/my-orders/', MyOrdersView.as_view(), name='my_orders'),
    path('orders/shop-orders/', ShopOrdersView.as_view(), name='shop_orders'),
    path('orders/accept/', AcceptOrderView.as_view(), name='accept_order'),
    path('orders/reject/', RejectOrderView.as_view(), name='reject_order'),
    path('orders/advance/', AdvanceOrderView.as_view(), name='advance_order'),
    path('orders/recommend-delivery/', DeliveryRecommendationView.as_view(), name='recommend_delivery'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('', include(router.urls)),
]

