from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    ProductViewSet,
    ShopViewSet,
    SignupView,
    LoginView,
    MeView,
    TokenRefreshView,
    SendOTPView,
    VerifyOTPView,
    ProductListView,
    ProductSearchView,
    ProductDetailView,
    ShopDetailView,
    ShopRankingView,
    CheckoutView,
    MyOrdersView,
    ShopOrdersView,
    AcceptOrderView,
    RejectOrderView,
    AdvanceOrderView,
    OrderTimeoutView,
    ProductShopsView,
    OrderDetailView,
    CategoryListView,
    WishlistViewSet,
    ShopAnalyticsView,
    ShopProductsListView,
    ShopToggleLiveInventoryView,
    ShopToggleOpenView,
    RiderStatusToggleView,
    RiderDashboardView,
    UpdateDeliveryAssignmentView,
    DeliveryRecommendationView,
    ShopDemandForecastView,
)
from .dashboard_views import (
    ShopRevenueTodayView,
    ShopRevenueMonthView,
    ShopTopProductsView,
    MarketSearchTrendsView,
    ShopLowStockView,
    ShopOutOfStockView,
    ShopExpiringProductsView,
    ShopSlowMovingProductsView,
    ShopWeatherView,
    ShopSalesReportView,
    ShopCustomerCRMView,
    ShopSendCustomerOfferView,
    ShopPromotionsView,
    ShopGrowthHubView,
    ShopUpgradeTierView,
    ShopSettingsView,
    ShopGlobalSearchView,
    ShopDashboardSummaryView,
)

from .admin_views import (
    AdminStatsView,
    AdminOrdersView,
    AdminOrderDetailView,
    AdminShopsView,
    AdminShopDetailView,
    AdminRidersView,
    AdminRiderDetailView,
    AdminUsersView,
    AdminUserDetailView,
    AdminProductsView,
    AdminProductDetailView,
)

router = DefaultRouter()
router.register(r'products', ProductViewSet, basename='product')
router.register(r'shops', ShopViewSet, basename='shop')
router.register(r'wishlist', WishlistViewSet, basename='wishlist')

urlpatterns = [
    path('auth/signup/', SignupView.as_view(), name='signup'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/me/', MeView.as_view(), name='auth_me'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('auth/send-otp/', SendOTPView.as_view(), name='send_otp'),
    path('auth/verify-otp/', VerifyOTPView.as_view(), name='verify_otp'),
    path('products/list/', ProductListView.as_view(), name='product_list'),
    path('products/search/', ProductSearchView.as_view(), name='product_search'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('products/detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/shops/', ProductShopsView.as_view(), name='product_shops'),
    path('shops/detail/<int:pk>/', ShopDetailView.as_view(), name='shop_detail'),
    path('shops/ranking/', ShopRankingView.as_view(), name='shop_ranking'),
    path('shops/analytics/', ShopAnalyticsView.as_view(), name='shop_analytics'),
    path('shops/demand-forecast/', ShopDemandForecastView.as_view(), name='shop_demand_forecast'),
    path('shop/dashboard/revenue-today/', ShopRevenueTodayView.as_view(), name='dashboard_revenue_today'),
    path('shop/dashboard/revenue-month/', ShopRevenueMonthView.as_view(), name='dashboard_revenue_month'),
    path('shop/dashboard/top-products/', ShopTopProductsView.as_view(), name='dashboard_top_products'),
    path('shop/dashboard/search-trends/', MarketSearchTrendsView.as_view(), name='dashboard_search_trends'),
    path('shop/dashboard/low-stock/', ShopLowStockView.as_view(), name='dashboard_low_stock'),
    path('shop/dashboard/out-of-stock/', ShopOutOfStockView.as_view(), name='dashboard_out_of_stock'),
    path('shop/dashboard/expiring-products/', ShopExpiringProductsView.as_view(), name='dashboard_expiring_products'),
    path('shop/dashboard/slow-moving/', ShopSlowMovingProductsView.as_view(), name='dashboard_slow_moving'),
    path('shop/dashboard/weather/', ShopWeatherView.as_view(), name='dashboard_weather'),

    path('shop/dashboard/reports/', ShopSalesReportView.as_view(), name='dashboard_reports'),
    path('shop/dashboard/customers/', ShopCustomerCRMView.as_view(), name='dashboard_customers'),
    path('shop/dashboard/customers/send-offer/', ShopSendCustomerOfferView.as_view(), name='dashboard_send_offer'),
    path('shop/dashboard/promotions/', ShopPromotionsView.as_view(), name='dashboard_promotions'),
    path('shop/dashboard/growth/', ShopGrowthHubView.as_view(), name='dashboard_growth'),
    path('shop/dashboard/growth/upgrade/', ShopUpgradeTierView.as_view(), name='dashboard_upgrade_tier'),
    path('shop/dashboard/settings/', ShopSettingsView.as_view(), name='dashboard_settings'),
    path('shop/dashboard/search/', ShopGlobalSearchView.as_view(), name='dashboard_global_search'),
    path('shop/dashboard/summary/', ShopDashboardSummaryView.as_view(), name='dashboard_summary'),

    path('shops/my-products/', ShopProductsListView.as_view(), name='shop_my_products'),
    path('shops/toggle-live/', ShopToggleLiveInventoryView.as_view(), name='shop_toggle_live'),
    path('shops/toggle-open/', ShopToggleOpenView.as_view(), name='shop_toggle_open'),
    path('riders/toggle-online/', RiderStatusToggleView.as_view(), name='rider_toggle_online'),
    path('riders/dashboard/', RiderDashboardView.as_view(), name='rider_dashboard'),
    path('riders/assignments/update/', UpdateDeliveryAssignmentView.as_view(), name='rider_assignment_update'),
    path('orders/checkout/', CheckoutView.as_view(), name='checkout'),
    path('orders/my-orders/', MyOrdersView.as_view(), name='my_orders'),
    path('orders/shop-orders/', ShopOrdersView.as_view(), name='shop_orders'),
    path('orders/accept/', AcceptOrderView.as_view(), name='accept_order'),
    path('orders/reject/', RejectOrderView.as_view(), name='reject_order'),
    path('orders/advance/', AdvanceOrderView.as_view(), name='advance_order'),
    path('orders/timeout/', OrderTimeoutView.as_view(), name='order_timeout'),
    path('orders/recommend-delivery/', DeliveryRecommendationView.as_view(), name='recommend_delivery'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),

    # Admin Portal APIs
    path('admin/dashboard-stats/', AdminStatsView.as_view(), name='admin_stats'),
    path('admin/orders/', AdminOrdersView.as_view(), name='admin_orders'),
    path('admin/orders/<int:pk>/', AdminOrderDetailView.as_view(), name='admin_order_detail'),
    path('admin/shops/', AdminShopsView.as_view(), name='admin_shops'),
    path('admin/shops/<int:pk>/', AdminShopDetailView.as_view(), name='admin_shop_detail'),
    path('admin/riders/', AdminRidersView.as_view(), name='admin_riders'),
    path('admin/riders/<int:pk>/', AdminRiderDetailView.as_view(), name='admin_rider_detail'),
    path('admin/users/', AdminUsersView.as_view(), name='admin_users'),
    path('admin/users/<int:pk>/', AdminUserDetailView.as_view(), name='admin_user_detail'),
    path('admin/products/', AdminProductsView.as_view(), name='admin_products'),
    path('admin/products/<int:pk>/', AdminProductDetailView.as_view(), name='admin_product_detail'),

    path('', include(router.urls)),
]

