# Generated by Django 6.0.6 on 2026-07-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_mode_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Confidence percentage (0-100) of the ML prediction', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recommended_delivery_mode',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('shop_delivery', 'Shop Delivery'), ('digibazaar_delivery', 'DigiBazaar Delivery')], help_text='ML predicted best delivery mode', max_length=50, null=True),
        ),
    ]
