# Generated by Django 6.0.5 on 2026-07-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_delivery_mode_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('predicted_quantity', models.FloatField(default=0.0)),
                ('actual_quantity', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(default=0.0)),
                ('mse', models.FloatField(default=0.0)),
                ('r2_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='core.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='core.shop')),
            ],
            options={
                'verbose_name': 'Demand Forecast',
                'verbose_name_plural': 'Demand Forecasts',
                'ordering': ['-date'],
                'unique_together': {('shop', 'product', 'date')},
            },
        ),
    ]
