# Generated by Django 6.0.5 on 2026-07-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marketsearchtrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_label',
            field=models.CharField(blank=True, default='', help_text="Display unit, e.g. '1 kg', '500 ml', '1 pc'", max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
