# Generated by Django 6.0.5 on 2026-08-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_baby_kids_to_instant_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='tier_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the paid tier expires.', null=True),
        ),
    ]
